spring:
  application:
    name: pulse-inventory

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer