CREATE TABLE orders(
    id VARCHAR(36) PRIMARY KEY,
    customer_id VARCHAR(36) NOT NULL,
    total_amount DECIMAL(10, 2) NOT NULL,
    item_sku VARCHAR(64) NOT NULL,
    quantity INT NOT NULL,
    status ENUM('PENDING', 'CONFIRMED', 'CANCELLED') default 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP
);